### PR TITLE
[update] update gymapi.pyi with better presentation

### PR DESCRIPTION
**Pull request by I-am-Future**
Hi Mr. @yzqin ,
   
After my previous [pull request](https://github.com/yzqin/isaacgym-stubs/pull/3), I have worked further to enhance the experience for the stub.

## Changes

1. **Docstring along coding.**

In previous commits, users need to "ctrl + left click" to navigate to the .pyi file for the detailed docstring (See the last issue [here](https://github.com/yzqin/isaacgym-stubs/issues/2)). Now, I have updated my automatic generation [scripts](https://github.com/I-am-Future/isaacgym-stubs-enhanced/blob/enhanced/enhance-pyi.ipynb), to produce the updated .pyi file. In this version, users can have docstrings along coding:

(VS Code)

image

(PyCharm)

image

which I think such functionality would boost developers more.

2. Minor fixes.

I have applied some minor fixes to the .pyi files:

(The return value for this function is Quat)
```py
# From
def from_axis_angle(self, *args, **kwargs) -> Any: ...

# To
def from_axis_angle(self, *args, **kwargs) -> Quat: ...
```

(Added import statement in the beginning)
```
from numpy import uint8, int16, uint32, float32
```

(Better representation)
```py 
# From
    angular_damping: float # property angular_damping Angular velocity damping for rigid bodies

# To
    angular_damping: float # property angular_damping: Angular velocity damping for rigid bodies
```

Thanks for considering my pull request!

### CODE REVIEW

**Comment by yzqin** [comment]
Thanks for the great effort. May I ask a small question about what drives the `Docstring along coding.` in your recent commit. Why can users now have docstrings along coding but not "ctrl + left click", which modification makes this happen?

Thanks!

**Comment by I-am-Future** [comment]
Thank you! That's a good question, and I'd like to share about my recent discoveries:

**1. Preliminaries.** According to [PEP257](https://peps.python.org/pep-0257/), The docstring is defined as:

> String literals **occurring immediately after a simple assignment** at the top level of a module, class, or `__init__` method are called “attribute docstrings”.

It means, the strings occurs just after signatures are called docstrings, like the example below:

```py
def function(a, b):
    """Do X and return a list."""
```

And the code below does NOT have a docstring, since "..." is the first expression after the signature.

```py
def function(a, b): ...
    """Do X and return a list."""
```

**2. Previous Version.** In the previous version of isaacgym-stub, the functions looks like below:

```py
    def acquire_net_contact_force_tensor(self, arg0: Sim) -> Tensor: ...
    ''' acquire_net_contact_force_tensor(self: Gym, arg0: Sim) -> Tensor
    Retrieves buffer for net contract forces. The buffer has shape (num_rigid_bodies, 3).
    ......
    '''
```

Note there is a "..." (Ellipsis) after the colon, which is the first expression after the expression. The attached string below is actually not a docstring of the method. Therefore, in VS Code and PyCharm, this docstring would not shown with code completion. So users need to "ctrl + left click", jump to the function signature, and view the strings attached below.

**3. Current Version.** Now, I have identified this problem, removing the Ellipsis after the colon:

```py
    def acquire_net_contact_force_tensor(self, arg0: Sim) -> Tensor: 
        ''' acquire_net_contact_force_tensor(self: Gym, arg0: Sim) -> Tensor
        Retrieves buffer for net contract forces. The buffer has shape (num_rigid_bodies, 3).
        ......
        '''
```

And now the attached string is the function docstring, so that it would appear with code completion in VS Code and PyCharm.

**4. More details.** The docstring would be rendered as markdown in VS Code and PyCharm. Continuous lines would be rendered in same line. 

image

To make a new line displayed, I insert blank rows between current rows to:

```py
    def acquire_net_contact_force_tensor(self, arg0: Sim) -> Tensor: 
        ''' acquire_net_contact_force_tensor(self: Gym, arg0: Sim) -> Tensor

        Retrieves buffer for net contract forces. The buffer has shape (num_rigid_bodies, 3).

        ......

        '''
```

So now the docstring would be rendered normally.

image

Thank you!

**Comment by I-am-Future** [comment]
Hi Mr. @yzqin ,
    
In the most recent commit of this PR, I have updated two GIFs in the README, which demonstrate the "docstrings along coding" better.

Thanks! 😃

**Comment by yzqin** [comment]
That is a really amazing update to improve the user experience and thank you so much for the detailed explanation! Great work!

**Pull request merged**
